---
- name: Set connection settings for all hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fail if ansible_ssh_private_key_file is not defined
      ansible.builtin.fail:
        msg: >
          Variable 'ansible_ssh_private_key_file' is not defined in group_vars/all.yml.
          Add the path to your SSH private key:
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      when: ansible_ssh_private_key_file is not defined

    - name: Set ansible_user and SSH key for all hosts
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_user: "{{ default_user }}"
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
      loop: "{{ groups['all'] }}"

    - name: Set ansible_become_pass for all hosts
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_become_pass: "{{ user_password }}"
      loop: "{{ groups['all'] }}"
      when: user_password is defined

- name: Hardening hosts
  hosts: all
  serial: 1
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  become: yes
  tags:
    - hardening

- name: Configure firewall
  hosts:
    - all
  roles:
    - geerlingguy.firewall
  become: true
  tags:
    - firewall

- name: Configure docker
  hosts:
    - all
  roles:
    - geerlingguy.docker
  become: true
  tags:
    - docker

- name: Configure remna server
  hosts:
    - central
  roles:
    - iphizic.remna-server
  become: true
  tags:
    - remna-server
    - remna

- name: Configure remna node
  hosts:
    - remna_node
  roles:
    - baikal
    - iphizic.remna-node
  become: true
  tags:
    - remna-node
    - remna

- name: Configure caddy
  hosts:
    - central
    - remna_node
  roles:
    - caddy
  become: true
  tags:
    - caddy
