{
 "title": "Telegram MTProto Proxy Status",
 "description": "Telegram MTProto Proxy Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(mtg_client_connections,alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "mtg_client_connections{alias=~\"$Node\", ip_family=\"ipv4\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Authentication Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "mtg_replay_attacks{alias=~\"$Node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(mtg_telegram_traffic{alias=~\"$Node\", direction=\"from_client\"}[30s])",
     "legendFormat": "i->{{alias}}"
    },
    {
     "expr": "delta(mtg_telegram_traffic{alias=~\"$Node\", direction=\"to_client\"}[30s])",
     "legendFormat": "o<-{{alias}}"
    }
   ]
  },
  {
   "title": "Telegram Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "label_replace(mtg_telegram_connections{alias=~\"$Node\", dc=\"0\"}, \"dci\", \"DC1\", \"dc\", \"(.*)\")",
     "legendFormat": "{{alias}} - {{dci}} ({{protocol}})"
    },
    {
     "expr": "label_replace(mtg_telegram_connections{alias=~\"$Node\", dc=\"1\"}, \"dci\", \"DC2\", \"dc\", \"(.*)\")",
     "legendFormat": "{{alias}} - {{dci}} ({{protocol}})"
    },
    {
     "expr": "label_replace(mtg_telegram_connections{alias=~\"$Node\", dc=\"2\"}, \"dci\", \"DC3\", \"dc\", \"(.*)\")",
     "legendFormat": "{{alias}} - {{dci}} ({{protocol}})"
    },
    {
     "expr": "label_replace(mtg_telegram_connections{alias=~\"$Node\", dc=\"3\"}, \"dci\", \"DC4\", \"dc\", \"(.*)\")",
     "legendFormat": "{{alias}} - {{dci}} ({{protocol}})"
    },
    {
     "expr": "label_replace(mtg_telegram_connections{alias=~\"$Node\", dc=\"4\"}, \"dci\", \"DC5\", \"dc\", \"(.*)\")",
     "legendFormat": "{{alias}} - {{dci}} ({{protocol}})"
    }
   ]
  }
 ]
}